### ISSUE TITLE
I have find a Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [paypal/permissions-sdk-php#19]
Hello:
I have find a Reflected XSS vulnerability in this sdk.

The vulnerability exists due to insufficient filtration of user-supplied data in “verification_code” HTTP REQUEST parameter that will be passed to “permissions-sdk-php-master\samples\GetAccessToken.php”. The infected source code is line 24, there is no protection on$_REQUEST['verification_code']; if $_REQUEST['verification_code'] contains evil js code, line 24 will trigger untrusted code to be excuted on the browser side.
![image](https://cloud.githubusercontent.com/assets/1484292/23160735/88454432-f862-11e6-8271-353adc039eb8.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/permissions-sdk-php-master/samples/GetAccessToken.php?verification_code="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![image](https://cloud.githubusercontent.com/assets/1484292/23160809/db785798-f862-11e6-920e-0051c37e588d.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech
Email: jgj212@gmail.com

**Comment by pp-randy** [comment]
Adding internal tracking: BTDXCLTS-283

**Comment by jaypatel512** [comment]
Hey @jgj212 !

As discussed in your PR, the samples are for training purposes only, and out intention is to keep it simple to understand the API process. It is expected from developers to use their due diligance on implementing these samples in real life.

However, we were able to add a layer of protection by discarding `samples` and other directories that are not useful from the archive, which is what composer uses to provide these packages. We really appreciate your concern. Feel free to create more PRs with other issues if you find any.
