### ISSUE TITLE
Double urldecode during authorization of the customer will replace + symbol with space symbol.

### ISSUE THREAD

**Issue by BC-ACherednichenko** [paypal/permissions-sdk-php#22]
### General information

* SDK/Library version: 3.9.1
* Environment: Sandbox and Production
* Language, language version, and OS: PHP 7.1 - but it does not matter

### Issue description
Hello PayPal team 

I catch the following issue - during the call of the method GetBasicPersonalData https://github.com/paypal/permissions-sdk-php/blob/master/lib/PayPal/Service/PermissionsService.php#L141 
double urldecode in $ret->init(PPUtils::nvpToMap($resp)) will corrupt any data in the response that has '+' symbol. As this method returns a basic user info after authorization, it has user's email, and email can contain ‘+’, it is the major place where issue happens, user email is getting corrupted ( '+' symbol will be replaced with space symbol) 

Those methods separately (PPMessage::init() and PPUtils::nvpToMap()) will not cause the issue, it really depends on the consumer, in our case, consumer https://github.com/paypal/permissions-sdk-php/blob/master/lib/PayPal/Service/PermissionsService.php#L141 . PermissionsService uses both those methods and it causes double urldecode which can affect any data with '+' symbol

Here is the flow of how issue appears:

- foo%2Bbar%40example.com came in response
- $ret->init(PPUtils::nvpToMap($resp)) will parse the response
- PPUtils::nvpToMap($resp) - https://github.com/paypal/sdk-core-php/blob/master/lib/PayPal/Core/PPUtils.php#L22 - will split the data in the response + url decode
- at this point email looks like this foo+bar@example.com
- then, $ret->init() is getting involved into the flow https://github.com/paypal/sdk-core-php/blob/master/lib/PayPal/Core/PPMessage.php#L68
- after init processed, email will look like this foo bar@example.com, as second urldecode will replace + symbol with the space symbol.

I have already added notes to the closed issue https://github.com/paypal/sdk-core-php/issues/59 , you can check it for additional info. 
Currently I am preparing PR, but as far as I see I have to apply PR in 2 different repo's, **paypal/sdk-core-php** and **paypal/permissions-sdk-php** 

1. modify PPUtils and add new method (that works without urldecode), it is located here https://github.com/paypal/sdk-core-php/blob/master/lib/PayPal/Core/PPUtils.php
in this repo paypal/sdk-core-php 
Another possible option is to add new argument to PPUtils::nvpToMap , `bool $urldecode = true`, so inside method we can define if we need to do URL decode, but I decided to keep SDK interfaces unchanged, please correct me if I am wrong

2. Use method that I defined above here https://github.com/paypal/permissions-sdk-php/blob/master/lib/PayPal/Service/PermissionsService.php#L141 (instead of PPUtils::nvpToMap($resp) ) in this repo paypal/permissions-sdk-php

But this part of SDK relies on paypal/sdk-core-php , so we will need to specify version that we are going to release with another part of the fix 

Current require in paypal/permissions-sdk-php
`"paypal/sdk-core-php":"3.*"`
Should  be 
`"paypal/sdk-core-php":">=version with fix in PPUtils"`

Can you provide a details about how we can properly handle such fix that affects two repos ? 

Thanks in advance

**Comment by devchristina** [comment]
Closing, not planned.
